##

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "kemora13",
    "email": "abdelghanielmouak@gmail.com",
  "password": "secret",
  "passwordConfirmation": "secret"
}

###
POST https://realtime-chat-gh1k.onrender.com/api/auth/login
Content-Type: application/json

{
  "username": "kemora13",
    "password": "secret"
}